[package]
name = "disk_quota_exceeded"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
clap = { version = "4.5.3", features = ["derive"] }
humansize = "2.1.3"
rayon = "1.9.0"
